import {assetURL} from './assets.js';
export class AudioDirector{
 constructor(caption=()=>{}){this.context=null;this.buffers=new Map();this.loops=new Map();this.cooldowns=new Map();this.caption=caption;this.active=new Set();this.settings={master:.65,music:.25,ambience:.4,effects:.65,muted:false};this.ready=false;this.failed=[];}
 async unlock(){if(!this.context){const C=window.AudioContext||window.webkitAudioContext;if(!C)return;this.context=new C();this.master=this.context.createGain();this.master.connect(this.context.destination);this.groups={};for(const name of ['music','ambience','effects','characters','creatures','cinematics']){const g=this.context.createGain();g.connect(this.master);this.groups[name]=g;}this.apply(this.settings);this.loading=this.load();}if(this.context.state==='suspended')await this.context.resume();}
 async load(){const names=['rain-field','wind-field','creature-field','rain','hum','echo','printer','phone','breath','music',...['wood','metal','paper','step','glass','stamp'].flatMap(k=>[k+'-0',k+'-1'])];await Promise.all(names.map(async name=>{try{const path='assets/audio/'+name+'.wav';const r=await fetch(assetURL(path));if(!r.ok)throw Error(path);const b=await this.context.decodeAudioData(await r.arrayBuffer());this.buffers.set(name,b);}catch{this.failed.push(name);}}));this.ready=true;if(this.failed.length)this.caption('Some audio unavailable / بعض الأصوات لم تُحمّل');}
 apply(settings){this.settings={...settings};if(!this.context)return;const t=this.context.currentTime;this.master.gain.setTargetAtTime(settings.muted?0:settings.master,t,.06);for(const k of ['music','ambience','effects','characters','creatures','cinematics'])this.groups[k].gain.setTargetAtTime(settings[k]??settings.effects,t,.06);}
 play(name,{volume=.5,x=240,muffled=false,category='effects',caption='',cooldown=.15}={}){if(caption)this.caption(caption);if(!this.context||!this.buffers.has(name)||this.context.state!=='running')return;const t=this.context.currentTime;if(t<(this.cooldowns.get(name)||0))return;this.cooldowns.set(name,t+cooldown);
  const s=this.context.createBufferSource();s.buffer=this.buffers.get(name);const gain=this.context.createGain();gain.gain.value=volume;const filter=this.context.createBiquadFilter();filter.type='lowpass';filter.frequency.value=muffled?700:18000;const pan=this.context.createStereoPanner();pan.pan.value=Math.max(-.8,Math.min(.8,(x-240)/240));s.connect(filter);filter.connect(gain);gain.connect(pan);pan.connect(this.groups[category]);this.active.add(s);s.onended=()=>{this.active.delete(s);s.disconnect();filter.disconnect();gain.disconnect();pan.disconnect();};s.start();window.dispatchEvent(new CustomEvent('echo:sound',{detail:{name,category,time:performance.now(),volume}}));
 }
 loop(name,wanted,volume,category='ambience'){
  if(!this.context||!this.ready)return;let l=this.loops.get(name);if(wanted&&!l){const s=this.context.createBufferSource();s.buffer=this.buffers.get(name);if(!s.buffer)return;s.loop=true;const gain=this.context.createGain();gain.gain.value=0;s.connect(gain);gain.connect(this.groups[category]);s.start();l={s,gain};this.loops.set(name,l);}if(l)l.gain.gain.setTargetAtTime(wanted?volume:0,this.context.currentTime,.5);
 }
 update(state,cinematic){if(!this.context)return;const active=!document.hidden;if(!state){this.loop('hum',active,.15);this.loop('music',active,.09,'music');for(const n of ['rain','rain-field','wind-field','breath'])this.loop(n,false,0);return;}this.loop('rain-field',active&&state.day>=3,state.world.window?.5:.19);this.loop('wind-field',active&&state.world.window,.2);this.loop('hum',active&&state.world.lights,.24);this.loop('music',active,cinematic?.25:.1,'music');this.loop('breath',active&&state.day>=10&&state.day<15&&!state.world.lights,.1);}
 impact(id,speed,x){const group={paper:'paper',record:'paper',folder:'paper',seal:'wood',key:'metal',lens:'glass',torch:'metal'}[id]||'wood';this.play(group+'-'+(Math.floor(performance.now()/300)%2),{volume:Math.min(.6,speed/220),x,cooldown:.16});}
 stopEffects(){for(const s of this.active){try{s.stop();}catch{}}this.active.clear();}
 async visibility(hidden){if(!this.context)return;if(hidden&&this.context.state==='running')await this.context.suspend();else if(!hidden&&this.context.state==='suspended')await this.context.resume().catch(()=>{});}
}
