import {ensureDesk,settleDay,purchase,UPGRADE_RULES} from './desk.js';
import {EVIDENCE,DECISIONS} from './content.js';
export function createDeskUI(api){const {$,node,button,tr,T,physics,audio,desk,save,openModal,render}=api;let state;return{refresh(s){state=s;renderDeskControls();},report(){report();},shop(){shop();}};
function renderDeskControls(){const host=$('desk-controls');host.replaceChildren();if(!state){host.append(node('p',tr('ابدأ الوردية لتستخدم المكتب. الصوت يبدأ عند أول تفاعل إذا المتصفح منع التشغيل التلقائي.','Start a shift to use the desk. If autoplay is blocked, sound begins with your first interaction.')));return;}const d=ensureDesk(state),disabled=!!state.cinematic||state.phase==='ending';
 for(const[id,ar,en,fn]of[
 ['unfold',d.opened?'اطوِ الطلب':'افرد الطلب',d.opened?'Fold request':'Unfold request',()=>{d.opened=!d.opened;audio.play('paper-0');}],
 ['rotate','لف الورقة','Rotate paper',()=>{physics.rotate('paper');audio.play('paper-1',{volume:.2});}],
 ['align','قارن النسختين','Align documents',()=>desk.align(state)],
 ['examine','فحص بالعدسة والضوء','Examine with lens and light',()=>desk.examine(state)],
 ['torch',d.torchOn?'أطفئ الكشاف':'شغّل الكشاف',d.torchOn?'Inspection light off':'Inspection light on',()=>{d.torchOn=!d.torchOn;audio.play('metal-0',{volume:.2});}],
 ['read','قراءة المستندات','Read documents',()=>{d.readable=!d.readable;render();}],
 ['report','تقرير الوردية','Shift report',report],
 ['supplies','طلبات التجهيزات','Equipment requests',shop]
 ]){const b=button(host,tr(ar,en),()=>{fn();renderDeskControls();save();},'quiet');b.dataset.desk=id;b.disabled=disabled;}
 const row=node('label',undefined,'stamp-mode');row.append(node('span',tr('وجه الختم للسحب: ','Seal face for dragging: ')));const select=node('select');select.id='stamp-mode';select.setAttribute('aria-label',tr('وجه الختم','Seal face'));for(const[v,ar,en]of[['ok','اعتماد','Approve'],['no','تصحيح','Return'],['fl','بلاغ','Flag']]){const op=node('option',tr(ar,en));op.value=v;select.append(op);}select.value=d.mode;select.disabled=disabled;select.onchange=()=>{d.mode=select.value;save();};row.append(select);host.append(row);}
function report(){if(!state)return;const d=ensureDesk(state),r=['dayEnd','decisionResult'].includes(state.phase)?settleDay(state):null;openModal(tr('تقرير الوردية '+state.day,'SHIFT REPORT '+state.day),'report');const rows=state.log.filter(v=>v.day===state.day),cases=rows.filter(v=>v.case),summary=r||{approved:cases.filter(v=>v.choice==='ok').length,rejected:cases.filter(v=>v.choice==='no').length,flagged:cases.filter(v=>v.choice==='fl').length,mistakes:cases.filter(v=>!v.correct).length,evidence:Object.entries(state.evidence).filter(([,v])=>v?.day===state.day).map(([k])=>k),reward:0,decisions:rows.filter(v=>v.flag).map(v=>v.flag)};
 $('modal-content').append(node('p',r?tr('الوردية اتقفلت والحساب اتسجل مرة واحدة.','Shift closed. The equipment allowance has been credited once.'):tr('تقرير مؤقت — الوردية لسه مفتوحة.','Interim report — the shift is still open.')));
 const grid=node('div',undefined,'report-grid');for(const[ar,en,value]of[['معتمد','Approved',summary.approved],['تصحيح','Returned',summary.rejected],['شذوذ','Flagged',summary.flagged],['أخطاء مراجعة','Review errors',summary.mistakes],['بدل تجهيزات','Equipment allowance',summary.reward],['الرصيد','Balance',d.credits]]){const box=node('div');box.append(node('strong',String(value)),node('span',tr(ar,en)));grid.append(box);}$('modal-content').append(grid,node('h3',tr('أدلة اليوم','Today’s evidence')));for(const id of summary.evidence)$('modal-content').append(node('p',T(EVIDENCE[id]?.title||id)));if(!summary.evidence.length)$('modal-content').append(node('p',tr('مفيش دليل جديد اتسجل النهارده.','No new evidence was filed today.')));
 for(const row of rows.filter(v=>v.flag)){const entry=DECISIONS[row.day-5],i=Number(row.choice)===1?1:0;$('modal-content').append(node('p',T(entry[3+i])));}
 $('modal-content').append(node('p',tr(`مؤن: ${state.inventory.food} · دواء: ${state.inventory.med} · ${state.infection?'العدوى مسجلة':'لا عدوى مسجلة'}`,`Food: ${state.inventory.food} · Medicine: ${state.inventory.med} · ${state.infection?'Infection recorded':'No infection recorded'}`)));button($('modal-content'),tr('طلبات التجهيزات','Equipment requests'),shop);save();}
function shop(){if(!state)return;const d=ensureDesk(state);openModal(tr('مخزن العهدة — طلب تجهيزات','EQUIPMENT REQUISITION'),'shop');$('modal-content').append(node('p',tr(`الرصيد: ${d.credits} قسائم. بدل الوردية ٢، وقسيمة لكل طلب راجعته صح. مفيش فلوس حقيقية.`,`Balance: ${d.credits} vouchers. Two per completed shift, plus one for each correctly reviewed request. No real money.`)));
 for(const[id,r]of Object.entries(UPGRADE_RULES)){const card=node('article',undefined,'result-card');card.append(node('h3',tr(r.ar,r.en)),node('p',tr(r.effectAr,r.effectEn)));const b=button(card,d.upgrades[id]?tr('تم الاستلام','Issued'):tr(`طلب — ${r.price} قسائم`,`Request — ${r.price} vouchers`),()=>{if(purchase(state,id)){audio.play('paper-0');save();shop();}});b.dataset.upgrade=id;b.disabled=!!d.upgrades[id]||d.credits<r.price;$('modal-content').append(card);}}

}
