import {deskState} from './desk-state.js';
export {deskState} from './desk-state.js';
import {currentCase,chooseCase,addEvidence} from './core.js';
import {localPoint,contains,clamp} from './physics.js';
export const UPGRADE_RULES={lens:{price:4,ar:'عدسة أرشيف ×٣',en:'Archive lens ×3',effectAr:'تكبير أكبر ومنطقة فحص أوسع؛ الأدلة نفسها متاحة بالعدسة الأصلية.',effectEn:'Larger zoom and examination area; every clue remains available with the original lens.'},light:{price:5,ar:'مصباح فحص ثابت',en:'Steady inspection light',effectAr:'يُظهر الحبر المخفي أسرع ويقلل تشويش الإضاءة.',effectEn:'Reveals latent ink faster and steadies the inspection beam.'},tray:{price:3,ar:'حافظة مقاومة للرطوبة',en:'Moisture-resistant tray',effectAr:'تقلل أثر الماء على الورقة إلى الربع وتُرتّب المستندات.',effectEn:'Reduces paper wetting to one quarter and aligns documents.'}};
export function ensureDesk(s){return s.desk||(s.desk=deskState());}
export function purchase(s,id){const d=ensureDesk(s),r=UPGRADE_RULES[id];if(!r||d.upgrades[id]||d.credits<r.price)return false;d.credits-=r.price;d.upgrades[id]=true;d.audit.push({day:s.day,type:'purchase',id,amount:-r.price});return true;}
export function settleDay(s){const d=ensureDesk(s);if(d.settled[s.day])return d.reports.find(r=>r.day===s.day);const rows=s.log.filter(r=>r.day===s.day),cases=rows.filter(r=>r.case),correct=cases.filter(r=>r.correct).length,reward=2+correct;d.credits+=reward;d.settled[s.day]=true;const report={day:s.day,approved:cases.filter(r=>r.choice==='ok').length,rejected:cases.filter(r=>r.choice==='no').length,flagged:cases.filter(r=>r.choice==='fl').length,correct,mistakes:cases.length-correct,reward,credits:d.credits,evidence:Object.entries(s.evidence).filter(([,v])=>v?.day===s.day).map(([k])=>k),decisions:rows.filter(r=>r.flag).map(r=>r.flag),food:s.inventory.food,med:s.inventory.med,infected:!!s.infection,purchases:d.audit.filter(r=>r.day===s.day&&r.type==='purchase').map(r=>r.id)};d.reports.push(report);return report;}
export function clueFor(s){if(s.day>=14&&s.evidence.self)return{id:'erasure',code:'M-07 / 3142',ar:'رقم 3142 تحت المحو؛ نفس الموظف اللي اختفت ذاكرته.',en:'3142 beneath the erasure: the same clerk whose memory was removed.'};if(s.day>=5&&s.evidence.transfer)return{id:'signature',code:'3142 / 02:14',ar:'توقيع 3142 يسبق النقل الساعة 02:14. قارنه بملفك.',en:'Signature 3142 precedes the 02:14 transfer. Compare it with your file.'};if(s.day>=2)return{id:'researcher',code:'S.M. / 3142',ar:'الحروف س.م. ونفس خط الشمال في هويات الباحث.',en:'S.M. and the same left-handed strokes recur across the researcher’s identities.'};return{id:null,code:'WINDOW 04',ar:'الألياف سليمة؛ الفحص مش بيقول إن كل طلب مزوّر.',en:'The fibres are intact. Examination does not make every request a forgery.'};}
// Bounded local particle simulation: water falls and wets documents, dust settles,
// steam rises, and electrical sparks expire. Ink drying is stored on each impression.
export class Materials{
 constructor(){this.particles=[];this.clock=0;this.seq=0;}
 emit(kind,x,y,n=5){for(let i=0;i<n&&this.particles.length<96;i++){const a=(this.seq++*2.399);this.particles.push({kind,x,y,vx:Math.cos(a)*(kind==='spark'?42:14),vy:kind==='water'?32:kind==='steam'?-12:-15-Math.abs(Math.sin(a))*9,life:kind==='steam'?2.2:1.5,age:0});}}
 step(dt,s,physics){if(!s)return;this.clock+=dt;const d=ensureDesk(s);d.smudge=Math.min(1,d.smudge+dt);const p=physics.body('paper');if(this.clock>.32){this.clock=0;if(s.world.window&&s.day>=3)this.emit('water',350+(this.seq%5)*5,195,1);if(s.world.lights)this.emit('dust',110+(this.seq%150),209,1);if(s.world.printer==='printing')this.emit('steam',396,200,1);}
 for(const m of this.particles){m.age+=dt;m.vy+=({dust:8,water:48,steam:-5,spark:55}[m.kind]||0)*dt;m.x+=m.vx*dt;m.y+=m.vy*dt;if(m.kind==='water'&&m.y>220&&contains(p,m)){d.wet=Math.min(1,d.wet+(d.upgrades.tray?.02:.08));m.age=m.life;}if(m.y>402){m.y=402;m.vy=0;m.vx*=Math.exp(-10*dt);} }this.particles=this.particles.filter(m=>m.age<m.life);
 d.wet=Math.max(0,d.wet-dt*(d.torchOn?.025:.006));for(const m of d.marks){m.dry=Math.min(1,m.dry+dt*(d.torchOn?.16:.07));if(m.dry<.8&&d.wet>.1)m.bleed=Math.min(1,(m.bleed||0)+dt*d.wet*.3);} }
 draw(x){for(const p of this.particles){x.globalAlpha=Math.min(.7,1-p.age/p.life);x.fillStyle={water:'#8cc5c9',dust:'#dac496',steam:'#c1c3b0',spark:'#ffc964'}[p.kind];x.fillRect(Math.round(p.x),Math.round(p.y),p.kind==='steam'?3:1,p.kind==='water'?4:1);}x.globalAlpha=1;}
}
export class Desk{
 constructor(physics,event=()=>{}){this.physics=physics;this.event=event;this.materials=new Materials();this.press=null;this.exposure=0;this.displayClue='';this.impacts=0;this.refraction=null;}
 bind(s){const d=ensureDesk(s),c=currentCase(s),id=c?.id||'shift-'+s.day;if(d.caseId!==id){d.caseId=id;d.opened=true;d.wet=0;this.physics.place('paper',171,274);this.physics.place('record',302,278);this.exposure=0;}return d;}
 validPaper(s,p){const b=this.physics.body('paper'),q=localPoint(b,p);return s.phase==='citizen'&&!s.cinematic&&ensureDesk(s).opened&&Math.abs(q.x)<b.w/2-12&&Math.abs(q.y)<b.h/2-12;}
 stamp(s,choice,assisted=false){if(this.press||s.phase!=='citizen'||s.cinematic)return false;const d=ensureDesk(s),paper=this.physics.body('paper'),seal=this.physics.body('seal');if(!['ok','no','fl'].includes(choice)||choice==='fl'&&!s.inspected[currentCase(s)?.id]){this.event('needProof');return false;}if(!d.opened){this.event('folded');return false;}if(assisted){this.physics.place('seal',paper.x+Math.sin(paper.angle)*-34,paper.y+Math.cos(paper.angle)*34);seal.angle=paper.angle;}if(!this.validPaper(s,seal)){d.smudge=0;this.smudgeAt={x:seal.x,y:seal.y};this.materials.emit('dust',seal.x,seal.y,8);this.event('deskImpact');seal.z=4;return false;}this.physics.release(true);seal.vx=seal.vy=0;this.press={age:0,choice,hit:false,paper:paper.id,caseId:d.caseId,x:seal.x,y:seal.y,angle:seal.angle};return true;}
 update(s,dt){if(!s||s.cinematic)return;const d=this.bind(s),p=this.physics.body('paper'),lens=this.physics.body('lens'),torch=this.physics.body('torch'),seal=this.physics.body('seal');this.materials.step(dt,s,this.physics);
 if(this.press){const a=this.press;a.age+=dt;seal.x=a.x;seal.y=a.y;seal.vx=seal.vy=0;seal.z=a.age<.1?10+a.age*30:a.age<.18?13*(.18-a.age)/.08:Math.max(0,6*(1-(a.age-.18)/.25));if(a.age>=.18&&!a.hit){a.hit=true;if(this.validPaper(s,seal)&&d.caseId===a.caseId){const q=localPoint(p,seal),result=chooseCase(s,a.choice);if(result.ok){d.marks.push({caseId:d.caseId,x:q.x,y:q.y,angle:seal.angle-p.angle,choice:a.choice,dry:0,bleed:d.wet*.4});d.marks=d.marks.slice(-50);p.vx+=3;p.vy+=6;p.z=1.5;d.ink=Math.max(.3,d.ink-.025);this.impacts++;this.materials.emit('dust',seal.x,seal.y,8);this.event('stamp',a.choice);}}}if(a.age>.48){this.press=null;seal.z=0;this.event('settled');}}
 const clue=clueFor(s),point={x:p.x-8*Math.sin(p.angle),y:p.y-8*Math.cos(p.angle)},radius=d.upgrades.lens?35:24;
 const lensOn=Math.hypot(lens.x-point.x,lens.y-7-point.y)<radius;
 const lit=s.world.lamp&&Math.hypot(p.x-261,p.y-270)<52||d.torchOn&&Math.hypot(torch.x-35-point.x,torch.y-point.y)<68;
 this.exposure=d.opened&&lensOn&&lit?Math.min(1.4,this.exposure+dt*(d.upgrades.light?1.65:1)):Math.max(0,this.exposure-dt*2);
 s.world.imprint=this.exposure/1.4;
 if(this.exposure>=1.4&&!d.examined['shift'+s.day]){d.examined['shift'+s.day]=true;this.displayClue=clue[s.language];if(clue.id)addEvidence(s,clue.id);if(s.phase==='citizen'){s.inspected[currentCase(s).id]=true;}this.event('clue',clue);}
 }
 align(s){this.physics.place('paper',177,276);this.physics.place('record',306,276);ensureDesk(s).opened=true;this.event('paper');}
 examine(s){const p=this.physics.body('paper');ensureDesk(s).opened=true;ensureDesk(s).torchOn=true;this.physics.place('lens',p.x,p.y-1);this.physics.place('torch',p.x+48,p.y-8);this.exposure=0;this.event('lens');}
 key(s,assisted=false){const key=this.physics.body('key');if(!s.flags.key){this.event('locked');return false;}if(assisted)this.physics.place('key',58,238);if(Math.hypot(key.x-58,key.y-238)>30)return false;s.world.archive=true;ensureDesk(s).folderOpen=true;addEvidence(s,'deleted');this.event('unlock');return true;}
}
