import {createDeskUI} from './desk-ui.js';
import {Desk,ensureDesk,settleDay,purchase,UPGRADE_RULES} from './desk.js';
import './stats.js';
import {assetURL} from './assets.js';
import {App as NativeApp} from '@capacitor/app';
import {Capacitor} from '@capacitor/core';
import {bi,text,CREDIT,COPYRIGHT,CITIZENS,DECISIONS,RECORDS,HOTSPOTS,HINTS,EVIDENCE,DEDUCTIONS,CINEMATICS,ENDINGS,CAST,RESEARCHER_LINES} from './content.js';
import {fresh,currentCase,greeting,variant,addEvidence,requirement,next,inspectCase,chooseCase,chooseDay,deduce,finish,SaveStore,META_KEY} from './core.js';
import {Physics,toWorld} from './physics.js';
import {Renderer} from './render.js';
import {AudioDirector} from './audio.js';
const $=id=>document.getElementById(id),node=(tag,content,cls)=>{const e=document.createElement(tag);if(content!==undefined)e.textContent=content;if(cls)e.className=cls;return e;};
let storage;try{storage=window.localStorage;}catch{storage={getItem:()=>null,setItem:()=>{throw Error('Storage unavailable');}};}
const store=new SaveStore(storage);let saved=store.read(),state=null,language=saved?.language||'ar',menuSettings=saved?.settings||fresh(1).settings,cinemaTime=0,printTimer=0,captionTimer=0,modalType='',lastFrame=0,imprintTime=0,lastImprint='',runCounter=0;
try{runCounter=JSON.parse(storage.getItem(META_KEY)||'{}').runs||0;}catch{}
const tr=(ar,en)=>language==='ar'?ar:en,T=v=>text(v,language);
const renderer=new Renderer($('scene'));
const audio=new AudioDirector(caption=>{if((state?.settings||menuSettings).captions){$('sound-caption').textContent=caption;captionTimer=2.5;}});
const physics=new Physics((id,speed,x)=>{audio.impact(id,speed,x);if(state?.day>=10&&!state.world.lights){state.world.noise=Math.min(1,state.world.noise+speed/1500);}});
const desk=new Desk(physics,(event,value)=>{
 if(event==='stamp'){audio.play('stamp-'+(desk.impacts%2),{volume:.7,x:physics.body('seal').x,caption:tr('الختم لمس الورقة — أثر الحبر اتسجل','Seal contacts paper — ink impression recorded')});render();save();}
 if(event==='settled')save();
 if(event==='clue'){audio.play('echo',{volume:.25});notice(value[language]);renderChrome();save();}
 if(event==='needProof')notice('افحص بالمكبّر أو الماسح قبل البلاغ.','Use the magnifier or scanner before flagging.');
 if(event==='folded')notice('افرد الورقة قبل الختم.','Unfold the document before stamping.');
 if(event==='deskImpact'){audio.play('wood-1',{volume:.35});notice('الختم لمس الخشب. مفيش قرار اتسجل.','The seal hit wood. No decision was recorded.');}
 if(event==='paper')audio.play('paper-1',{volume:.45});
 if(event==='lens')audio.play('glass-0',{volume:.25});
 if(event==='locked')notice('المفتاح ده لسه مع سمير؛ اطلب مساعدته في اليوم التاسع.','Samir still has this key. Ask for his help on day nine.');
 if(event==='unlock'){audio.play('metal-1',{volume:.5});notice('المفتاح طابق القفل. الأسماء المحذوفة في الحافظة.','The key fits. Deleted names are inside the folder.');render();save();}
});renderer.desk=desk;
const deskUI=createDeskUI({$,node,button,tr,T,physics,audio,desk,save,openModal,render});
function renderDeskControls(){deskUI.refresh(state);}
function notice(ar,en){$('notice').textContent=en===undefined?ar:tr(ar,en);}
function save(){if(!state)return;state.language=language;state.props=physics.snapshot();const ok=store.write(state);$('save-status').textContent=ok?tr('محفوظ على الجهاز','Saved on this device'):tr('الحفظ غير متاح — صدّر نسخة','Saving unavailable — export a copy');if(ok)saved=state;}
function button(parent,label,action,cls=''){const b=node('button',label,cls);b.type='button';b.addEventListener('click',()=>{audio.unlock();action();});parent.append(b);return b;}
function portrait(actor){const el=$('portrait');el.hidden=!actor;if(actor){el.style.backgroundImage=`url("${assetURL('assets/characters/'+actor+'.png')}")`;el.setAttribute('aria-label',T(CAST.find(c=>c[0]===actor)?.slice(1,3)));}}
function applyLanguage(){document.documentElement.lang=language;document.documentElement.dir=language==='ar'?'rtl':'ltr';$('language').textContent=tr('English','العربية');$('scene').setAttribute('aria-label',tr('مكتب التحقيق. كل الأدوات متاحة بأزرار أسفل المشهد.','Investigation desk. All tools are also accessible using the buttons below.'));}
function applySettings(){const settings=state?.settings||menuSettings;audio.apply(settings);physics.lensSensitivity=settings.lensSensitivity||1;document.documentElement.style.setProperty('--text-scale',settings.textSize);document.documentElement.classList.toggle('reduced',settings.reducedMotion);}
function renderChrome(){applyLanguage();applySettings();
 const d=state?.day||1;$('day-number').textContent=String(d).padStart(2,'0');$('chapter').textContent=state?tr('السجل المدني / الوردية '+d,'CIVIL REGISTRY / SHIFT '+String(d).padStart(2,'0')):tr('أصداء تحت الختم / آخر ملف','ECHOES BENEATH THE SEAL / THE LAST FILE');
 $('case-label').textContent=tr('ملف الوردية','SHIFT DOSSIER');$('workbench-title').textContent=tr('أدوات المكتب','DESK INSTRUMENTS');$('input-hint').textContent=tr('لمس · سحب · فحص','TAP · DRAG · INSPECT');$('journal-label').textContent=tr('دفتر التحقيق','Investigation journal');$('evidence-label').textContent=tr('أدلة محفوظة','EVIDENCE FILED');$('links-label').textContent=tr('استنتاجات','DEDUCTIONS');$('imprint-label').textContent=tr('الأشياء تتذكر','OBJECTS REMEMBER');$('imprint-title').textContent=tr('ما تركه الحبر','What the ink remembers');$('imprint-help').textContent=tr('حرّك العدسة فوق الحبر الصغير، ووجّه الكشاف نحوه. الأدلة المكتشفة محفوظة في الدفتر.','Move the lens over the microprint and aim the light at it. Discovered evidence is filed in the journal.');$('place-paper').textContent=tr('افحص الأثر بالعدسة والضوء','Examine trace with lens and light');$('reset-props').textContent=tr('رتّب المكتب','Reset desk objects');$('menu-button').textContent=tr('حفظ والعودة للقائمة','Save and return to menu');$('credits').textContent=tr('عن اللعبة','Credits');$('install').textContent=tr('تثبيت','Install');$('margin-note').textContent=tr('الحقيقة لا تختفي. تتغيّر طريقة كتابتها.','The truth does not disappear. Only the way it is written.');
 $('objective').textContent=state?T(HINTS[d]):tr('15 وردية. 14 اسمًا مفقودًا. وتوقيع واحد لا تتذكره.','15 shifts. 14 missing names. One signature you cannot remember.');$('evidence-count').textContent=String(Object.keys(state?.evidence||{}).length).padStart(2,'0');$('links-count').textContent=Object.keys(state?.deductions||{}).length+'/4';$('supplies').textContent=state?tr(`مؤن ${state.inventory.food} · دواء ${state.inventory.med} · ${state.infection?'مصاب':'مستقر'}`,`Food ${state.inventory.food} · Medicine ${state.inventory.med} · ${state.infection?'INFECTED':'STABLE'}`):tr('عربي / English · حفظ محلي','Arabic / English · Local saves');$('weather').textContent=d<3?'06:14 / CLEAR':d<10?'17:14 / RAIN':'21:14 / CURFEW';
 $('chapter-track').replaceChildren(...Array.from({length:15},(_,i)=>{const e=node('i');e.className=i<d?'done':'';return e;}));
 $('tools').replaceChildren();for(const h of HOTSPOTS){const b=button($('tools'),T(h.label),()=>interact(h.id));b.dataset.tool=h.id;b.disabled=!state||!!state.cinematic||state.phase==='ending';}
 for(const id of ['place-paper','reset-props','journal','menu-button'])$(id).disabled=!state||!!state.cinematic;
}
function render(){layoutContext();if(state){desk.bind(state);if(['dayEnd','decisionResult'].includes(state.phase))settleDay(state);}renderChrome();renderDeskControls();$('actions').replaceChildren();$('documents').replaceChildren();$('request').textContent='';$('cinematic').hidden=!state?.cinematic;
 if(!state){portrait(null);$('speaker').textContent='ECHOES BENEATH THE SEAL';$('story-title').textContent=tr('كل ختم يترك أثرًا.','Every seal leaves a trace.');$('dialogue').textContent=tr('أنت الموظف الجديد في الشباك 4. راجع الوثائق، حرّك الأشياء، واربط ما يتذكّره الورق بما يحاول النظام نسيانه.','You are the new clerk at Window 4. Inspect documents, move objects, and connect what the paper remembers with what the system wants forgotten.');button($('actions'),tr('ابدأ وردية جديدة','Start a new run'),()=>{if(saved&&saved.phase!=='ending')confirmFresh();else startFresh();});if(saved&&saved.phase!=='ending')button($('actions'),tr('كمّل من الحفظ','Continue saved run'),()=>resume(saved),'secondary');return;}
 const s=state,c=currentCase(s);if(s.cinematic){const film=s.cinematic===16?{title:ENDINGS[s.ending][0],caption:ENDINGS[s.ending][1]}:CINEMATICS[s.cinematic-1];$('cinema-title').textContent=T(film.title);$('cinema-caption').textContent=T(film.caption);$('cinema-kicker').textContent=s.cinematic===16?'EPILOGUE':`SHIFT ${String(s.day).padStart(2,'0')} / MEMORY FRAGMENT`;$('skip-cinema').textContent=tr('تخطّي المشهد','Skip scene');}
 portrait(c&&['citizen','result'].includes(s.phase)?c.actor:s.day===8?'hala':s.day===6?'yasser':[5,13,14].includes(s.day)?'researcher':null);
 $('speaker').textContent=tr('الشباك 4 / السجل المدني','WINDOW 4 / CIVIL REGISTRY');$('story-title').textContent=tr('الوردية '+s.day,'Shift '+s.day);
 if(s.phase==='intro'){$('dialogue').textContent=T(CITIZENS[s.day-1].n);action(tr('استقبل المواطن','Receive citizen'),advance);}
 if(s.phase==='citizen'){$('speaker').textContent=T(c.nm);$('story-title').textContent=T(c.rq);$('dialogue').textContent=T(c.say)+' '+T(greeting(s,c));$('request').textContent=s.asked[c.id]?tr('ردّه: ','Reply: ')+T(reply(s,c)):tr('قارن البيانات أو افحص بالماسح قبل الإبلاغ.','Compare the fields or scan before flagging.');renderDocuments(c);$('documents').hidden=!state.desk.readable;
  action(tr('اعتماد بالختم','Approve with seal'),()=>makeCase('ok'));action(tr('رفض / تصحيح','Reject / correct'),()=>makeCase('no'),'danger');action(tr('بلّغ عن شذوذ','Flag anomaly'),()=>makeCase('fl'),'secondary');action(tr('اسأله عن الطلب','Ask about the request'),()=>{s.asked[c.id]=true;if(c.actor==='mahmoud')addEvidence(s,'s07');notice(tr('الشهادة اتسجلت؛ قارنها بالورق.','Statement noted; compare it with the papers.'));render();save();},'quiet');
 }
 if(s.phase==='result'){$('documents').hidden=true;$('dialogue').textContent=(s.lastChoice?.correct?tr('قرار موثّق. ','Verified decision. '):tr('راجع القرار. ','Review your decision. '))+T(s.lastChoice?.explanation||c.w);action(s.day===4?tr('شاهد التحوّل وتابع','Witness the transformation and continue'):tr('التالي','Continue'),advance);}
 if(s.phase==='dayEnd'){$('dialogue').textContent=T(CITIZENS[s.day-1].e)||tr('الاسم تغيّر. أثره بقي.','The name changed. Its imprint stayed.');action(tr('ابدأ اليوم التالي','Start next day'),advance);}
 if(['investigate','choice','decisionResult'].includes(s.phase)){const d=DECISIONS[s.day-5];$('story-title').textContent=T(CINEMATICS[s.day-1].title);$('dialogue').textContent=s.phase==='decisionResult'&&s.day===13&&s.flags.blocked13?tr('تركت الملفات مختومة؛ السجل رفض تصريح الدخول.','You leave the files sealed; the registry refused access.'):T(d[s.phase==='decisionResult'?3+s.choiceIndex:0]);
  if(s.phase==='investigate')$('request').textContent=T(HINTS[s.day]);
  if(s.phase==='choice'){for(let i=0;i<2;i++){const b=action(s.day===13&&s.flags.blocked13&&i===1?tr('اترك الملفات مقفولة','Leave the files sealed'):T(d[1+i]),()=>{if(chooseDay(s,i)){render();save();}else notice('هذا المسار يحتاج تصريحًا ودليلًا متاحًا. يمكنك اختيار المسار البديل.','This path requires clearance and accessible evidence. You can choose the alternative path.');},i?'danger':'');if(i===0&&(s.day===12&&!s.flags.key&&!s.flags.sec||s.day===13&&!s.world.printed.includes('echo')||s.day===14&&!s.evidence.self))b.disabled=true;}
   if(s.day===6&&s.evidence.cctv||s.day===8&&s.evidence.hala||s.day===13&&s.evidence.researcher&&s.world.printed.includes('echo'))action(s.day===6?tr('سلّم نسخة واحتفظ بالأصل','Hand over a copy; keep the original'):s.day===8?tr('نسخة لهالة مقابل متابعة المصابين','Give Hala a copy; arrange follow-up'):tr('اطبع الملفات واطلب شهادة سليم','Print the files and ask Salim to testify'),()=>{chooseDay(s,2);render();save();},'secondary');
  }
  if(s.phase==='decisionResult')action(tr('ابدأ اليوم التالي','Start next day'),advance);
 }
 if(s.phase==='final'){$('story-title').textContent=tr('آخر ختم.','One final seal.');$('dialogue').textContent=tr('أمامك الأدلة والناس الذين أثّرت فيهم. اربط الشهادات في الدفتر، ثم اختار ما ستفعله بالحقيقة.','The evidence and the people you affected are before you. Connect the testimony in your journal, then decide what to do with the truth.');for(const[id,ar,en]of[['truth','اكشف الحقيقة','Reveal the truth'],['silence','اخفِ الحقيقة','Bury the truth'],['leave','اترك المدينة','Leave the city'],['sac','ضحِّ لإنقاذ الناجين','Sacrifice for the survivors'],['file','افتح ملفك الأخير','Open your last file']])action(tr(ar,en),()=>{if(finish(s,id)){cinemaTime=0;audio.play('echo');render();save();}},id==='silence'?'danger':'secondary');}
 if(s.phase==='ending'){$('story-title').textContent=T(ENDINGS[s.ending][0]);$('dialogue').textContent=T(ENDINGS[s.ending][1]);$('request').textContent=CREDIT;action(tr('ابدأ حكاية جديدة','Begin a new story'),startFresh);action(tr('راجع دفتر القضية','Review the case journal'),openJournal,'secondary');}
 if([2,5,8,12,14].includes(s.day)&&!s.cinematic&&s.phase!=='ending')action(tr('افحص زيارة الباحث','Inspect the researcher’s visit'),()=>{openModal(tr('الزائر صاحب القفاز','The visitor with the glove'),'researcher');const line=RESEARCHER_LINES[s.day<5?0:s.day<12?1:2];$('modal-content').append(node('p',T(line)),node('p',tr('رقم الموظف 3142. الهوية تتغير؛ القفاز الأيسر وخط اليد لا يتغيران.','Employee 3142. The identity changes; the left glove and handwriting do not.')));button($('modal-content'),tr('قارن الهويات وسجّل الأثر','Compare identities and file the trace'),()=>{addEvidence(s,'researcher');if(!s.flags['visit'+s.day]){s.relationships.salim++;s.flags['visit'+s.day]=1;}closeModal();notice('اتحفظ دليل هويات الباحث.','Researcher’s aliases filed.');render();save();});},'quiet');
 if(s.cinematic)$('actions').querySelectorAll('button').forEach(b=>b.disabled=true);
}
function layoutContext(){const main=$('scene-wrap').parentElement,side=document.querySelector('.sidebar');if(innerWidth>650){side.prepend($('actions'));side.prepend($('story'));}else{main.insertBefore($('story'),$('scene-wrap'));$('desk-controls').after($('actions'));}}
function reply(s,c){const variants=c.rec.s==='p7'?[bi('فاكر ريحة المطهّر… والراجل اللي بيكتب بإيده الشمال.','I remember disinfectant… and the man who writes with his left hand.'),bi('قالوا لي الاسم هيرجع بعد الجلسة. رجع الرقم بس.','They said my name would return after the session. Only the number returned.'),bi('معصمي عليه سوار، لكن أنا مش فاكر مين لبّسه لي.','There is a band on my wrist. I cannot remember who put it there.')]:c.a==='ok'?[bi('أقدر أستنى الفحص. محتاج النسخة المعتمدة للمستشفى.','I can wait for the check. The hospital needs the certified copy.'),bi('راجع الاسم والتاريخ. أخدتهم من آخر نسخة رسمية.','Check the name and date. I copied them from the last official record.'),bi('إنت المسؤول عن التوثيق؛ اسألني لو فيه حاجة ناقصة.','You authenticate the record; ask me if anything is missing.')]:[bi('البطاقة معايا من قبل تحديث السجل. قارن النسختين.','I had this card before the registry update. Compare both copies.'),bi('ما طلبتش تغيير المعلومة دي. مين عدّلها؟','I never requested that change. Who edited it?'),bi('مش هتلاقي تفسير في عدد الملفات؛ شوف التوقيع والتاريخ.','The number of files will not explain it. Check the signature and date.')];return variants[variant(s,c.id+':reply',variants.length)];}
function action(label,fn,cls){return button($('actions'),label,fn,cls);}
function renderDocuments(c){for(const record of [false,true]){const card=node('article',undefined,'document');card.append(node('h3',record?tr('سجل النظام','REGISTRY RECORD'):tr('بطاقة الهوية','IDENTITY CARD')));const rows=[[tr('الاسم','Name'),T(c.nm),false],[tr('الميلاد','Born'),record?c.rec.dob:c.dob,c.rec.dob!==c.dob],[tr('الرقم','ID'),c.id,false]];if(record)rows.push([tr('الحالة','Status'),state.inspected[c.id]?T({alive:bi('على قيد الحياة','Alive'),dead:bi('متوفى 2024','Deceased 2024'),dup:bi('سجلان لنفس الشخص','Two records, one person'),p7:bi('مريض 07','Patient 07')}[c.rec.s]):tr('افحص النظام أو الماسح','Inspect in database or scanner'),c.rec.s!=='alive']);for(const[label,value,conflict]of rows){const b=button(card,'',()=>{if(conflict){inspectCase(state);notice('تم تحديد تعارض. القرار متاح الآن.','Contradiction marked. You can now flag the record.');render();save();}else{b.classList.toggle('marked');notice('قارِن نفس الحقل في المستند الآخر.','Compare this field with the other document.');}});b.append(node('span',label),node('strong',value));}card.append(node('small',record?'CIVIL-DB / VERIFIED COPY':'REPUBLIC REGISTRY / WINDOW 04'));$('documents').append(card);}}
function startFresh(){let meta={};try{meta=JSON.parse(storage.getItem(META_KEY)||'{}');}catch{}if(state)meta.lastVariants={...state.history};else if(saved)meta.lastVariants={...saved.history};meta.runs=(meta.runs||0)+1;runCounter=meta.runs;try{storage.setItem(META_KEY,JSON.stringify(meta));}catch{}
 const seed=crypto.getRandomValues(new Uint32Array(1))[0];state=fresh(seed,language,meta);state.settings={...menuSettings,reducedMotion:menuSettings.reducedMotion||matchMedia('(prefers-reduced-motion: reduce)').matches};physics.reset();desk.press=null;cinemaTime=0;printTimer=0;lastImprint='';closeModal();audio.unlock();render();save();$('scene-wrap').scrollIntoView({block:'start'});}
function confirmFresh(){openModal(tr('وردية جديدة','A new run'),'confirm');$('modal-content').append(node('p',tr('هتبدأ من اليوم الأول بزيارات وحوارات متغيرة. الحفظ الحالي هيتحفظ كنسخة احتياطية.','Start on day one with varied visits and dialogue. The current save is retained as a backup.')));button($('modal-content'),tr('ابدأ من جديد','Start over'),startFresh);}
function resume(s){state=s;desk.press=null;language=s.language;menuSettings={...s.settings};physics.reset(s.props);cinemaTime=0;imprintTime=0;printTimer=0;lastImprint='';audio.unlock();render();save();$('scene-wrap').scrollIntoView({block:'start'});if(store.error)notice(store.error);}
function advance(){if(!state)return;const oldDay=state.day;audio.stopEffects();desk.press=null;next(state);if(state.day!==oldDay){physics.reset();imprintTime=0;lastImprint='';cinemaTime=0;audio.play('step-0',{caption:tr('خطوات في الممر','Footsteps in the corridor'),muffled:true});}render();save();}
function makeCase(choice){if(!state||desk.press)return;ensureDesk(state).mode=choice;desk.stamp(state,choice,true);renderDeskControls();}
function fileEvidence(id){if(addEvidence(state,id)){audio.play('echo',{volume:.4});renderer.burst(260,214);notice(tr('دليل جديد: ','New evidence: ')+T(EVIDENCE[id]?.title||id));}}
function interact(id){if(!state||state.cinematic||state.phase==='ending')return;const s=state,w=s.world;audio.unlock();audio.play('wood-0',{volume:.15});
 if(id==='computer'){openDatabase();return;}
 if(id==='scanner'){const c=currentCase(s);if(s.phase!=='citizen'||!c){notice('ضع بطاقة المواطن أمام الماسح أولًا.','Receive a citizen before scanning their ID.');return;}inspectCase(s);if(c.rec.s==='p7')fileEvidence('s07');notice(c.a==='ok'?tr('الماسح: البيانات والتوقيع متطابقان.','Scanner: fields and signature match.'):tr('الماسح: اختلاف في بيانات السجل. قارن الحقول.','Scanner: registry mismatch. Compare the fields.'));audio.play('printer',{volume:.2});}
 if(id==='drawer'){w.drawer=!w.drawer;notice(w.drawer?tr('الدرج مفتوح. الورق القديم متاح للفحص.','Drawer opened. Old papers are available for inspection.'):tr('الدرج مقفول.','Drawer closed.'));if(s.day>=5&&w.drawer)fileEvidence('transfer');requirement(s,'drawer');}
 if(id==='camera'){if(s.day>=6){fileEvidence('cctv');requirement(s,'camera');}else notice('الكاميرا سجّلت بداية الوردية.','The camera recorded the start of the shift.');}
 if(id==='window'){w.window=!w.window;if(s.day>=7)fileEvidence('street');requirement(s,'window');notice(s.day>=7?tr('نفس الوجوه تظهر على طريق المستشفى. النافذة المفتوحة تحرّك الورق.','The same faces appear on the hospital road. The open window stirs the paper.'):tr('النافذة تغيّر حركة الهواء والصوت.','The window changes the airflow and sound.'));audio.play('glass-0',{volume:.2,x:376});}
 if(id==='door'){w.door=!w.door;if(s.day>=6)w.barricade=true;requirement(s,'door');notice('خطوات وراء الباب. اقفله لكتم الصوت.','Footsteps behind the door. Close it to muffle the sound.');audio.play('step-1',{x:448,muffled:!w.door,caption:tr('خطوات / يمين المكتب','Footsteps / right of desk')});}
 if(id==='lights'){w.lights=!w.lights;if(!w.lights&&s.day>=10)desk.materials.emit('spark',243,198,10);if(s.day>=11)fileEvidence('sound');requirement(s,'lights');notice(w.lights?tr('الضوء أوقف اقتراب المصاب.','Light stopped the infected from approaching.'):tr('في الظلام، الأصوات النشطة تجذب المصاب. المصباح يفضل شغال.','In the dark, active sounds attract the infected. The desk lamp remains on.'));}
 if(id==='lamp'){w.lamp=!w.lamp;notice(w.lamp?tr('المصباح شغال. ضع الورقة في دائرة الضوء.','Lamp on. Place the paper in its light.'):tr('المصباح مقفول.','Lamp off.'));}
 if(id==='phone'){if(s.day===9){fileEvidence('call');requirement(s,'phone');notice('سمير: المفتاح تحت الدولاب. الأرشيف يفتح ممر الملحق.','Samir: the key is under the cabinet. The archive opens the annex passage.');}else if(s.day>=11)notice('الشبكة مقطوعة. الجرس المحلي يقدر يشتغل.','The network is down. The local bell still works.');else notice(s.day<5?tr('مكالمة عن ورقة ناقصة. الرقم مكتوب بخط مألوف.','A call about a missing paper. The number is written in familiar handwriting.'):tr('صوت: لا تفتح ملف 07.','A voice: do not open file 07.'));audio.play('phone',{x:320,caption:tr('جرس التليفون / وسط المكتب','Telephone bell / centre desk')});w.noise=Math.min(1,w.noise+.4);}
 if(id==='archive'){desk.key(s,true);return;}
 if(id==='printer'){if(w.printer==='ready'){const job=w.printJob;w.printed.push(job);w.printer='idle';w.printJob=null;fileEvidence(job);if(job==='echo')requirement(s,'print:echo');physics.place('paper',302,279);notice('جمعت النسخة المطبوعة. محفوظة في دفتر التحقيق.','Printed copy collected and filed in the journal.');}else if(w.printer==='jam'){w.printer='printing';printTimer=1.2;notice('تم فك الورقة. الطباعة بتكمل.','Paper cleared. Printing resumes.');}else notice(w.printer==='printing'?tr('الطابعة شغالة؛ الورقة هتظهر خلال ثواني.','Printer working; the sheet will emerge in a moment.'):tr('اطبع نتيجة من الكمبيوتر، ثم اجمع النسخة هنا.','Print a database result, then collect the copy here.'));}
 render();save();
}
function openModal(title,type){modalType=type;$('modal-title').textContent=title;$('modal-content').replaceChildren();if(!$('modal').open)$('modal').showModal();}
function closeModal(){if($('modal').open)$('modal').close();modalType='';}
$('close-modal').onclick=closeModal;
$('modal').addEventListener('cancel',()=>{modalType='';});
function openDatabase(){openModal(tr('قاعدة السجل المدني','CIVIL REGISTRY DATABASE'),'database');const search=node('input',undefined,'search');search.type='search';search.placeholder=tr('اسم أو رقم: هالة، ECHO، S07، YOU…','Name or ID: Hala, ECHO, S07, YOU…');search.setAttribute('aria-label',tr('بحث في السجل','Search registry'));const results=node('div');$('modal-content').append(search,results);search.addEventListener('input',()=>searchDatabase(search.value,results));searchDatabase('',results);search.focus();}
function searchDatabase(query,target){target.replaceChildren();const q=query.trim().toLowerCase();if(!q){target.append(node('p',tr('ابحث عن اسم أو رقم ملف. تلميح اليوم موجود في بطاقة الوردية.','Search by a name or file number. Today’s hint appears on the shift dossier.')));return;}
 const s=state;const all=[...Object.values(s.cases).flat().map(c=>({n:[c.nm.ar,c.nm.en],id:c.id,s:c.rec.s,dob:c.rec.dob,min:1,citizen:c})),...RECORDS.map(r=>({...r,ev:r.ev==='del'?'deleted':r.ev}))];
 for(const r of all.filter(r=>s.day>=r.min&&[...r.n,r.id].some(v=>v.toLowerCase().includes(q)))){const card=node('article',undefined,'result-card');card.append(node('h3',T(r.n)+' / '+r.id));const locked=r.lock&&!r.lock.some(k=>s.flags[k]);if(locked){card.append(node('p',tr('ملف مقيّد. محتاج تصريح أو دليل سابق.','Restricted file. Requires clearance or earlier evidence.')));if(s.day===13&&r.ev==='echo'||s.day===14&&r.ev==='self')button(card,tr('سجّل رفض الدخول وتابع','Record the access refusal and continue'),()=>{s.flags['blocked'+s.day]=1;requirement(s,s.day===13?'print:echo':'self');closeModal();render();save();});}else{
  card.append(node('p',r.citizen?tr('الميلاد: ','Born: ')+r.dob+' · '+T({alive:bi('حي','Alive'),dead:bi('متوفى 2024','Deceased 2024'),dup:bi('سجل مكرر','Duplicate record'),p7:bi('مريض 07','Patient 07')}[r.s]):T(EVIDENCE[r.ev]?.note||r.note)));
  if(r.citizen){s.inspected[r.citizen.id]=true;}
  if(r.ev){const ev=r.ev;button(card,tr('فحص وحفظ المعلومة','Inspect and file information'),()=>{if(EVIDENCE[ev])fileEvidence(ev);requirement(s,ev);if(ev==='self')s.flags.self=1;render();save();});button(card,tr('اطبع نسخة','Print a copy'),()=>{if(s.world.printer!=='idle'){notice('اجمع الورقة السابقة أو فك التعليق أولًا.','Collect the previous sheet or clear the jam first.');return;}s.world.printer='printing';s.world.printJob=ev;printTimer=0;audio.play('printer',{x:395,caption:tr('الطابعة تسحب الورقة','Printer feeds a sheet')});s.world.noise=Math.min(1,s.world.noise+.35);closeModal();notice('جاري الطباعة. اجمع الورقة من الطابعة.','Printing. Collect the sheet from the printer.');save();});}
 }target.append(card);}
 if(!target.childElementCount)target.append(node('p',tr('لا توجد نتائج متاحة في هذه الوردية.','No accessible results in this shift.')));save();}
function openJournal(){if(!state)return;openModal(tr('دفتر التحقيق / اربط الأدلة','INVESTIGATION JOURNAL / CONNECT EVIDENCE'),'journal');const desc=node('p',tr('اختار دليلين، ثم اختار الاستنتاج المدعوم بهما. جمع الأدلة وحده لا يكفي.','Select two pieces of evidence, then choose the conclusion they support. Collecting them alone is not enough.'));const list=node('div',undefined,'journal-list'),box=node('div',undefined,'deduction-box');const selected=[];$('modal-content').append(desc,list,box);box.textContent=tr('اختار دليلين من القائمة.','Choose two pieces of evidence.');
 for(const[id,e]of Object.entries(EVIDENCE)){if(!state.evidence[id])continue;const b=button(list,'',()=>{const i=selected.indexOf(id);if(i>=0)selected.splice(i,1);else{if(selected.length===2)selected.shift();selected.push(id);}list.querySelectorAll('button').forEach(el=>el.classList.toggle('selected',selected.includes(el.dataset.evidence)));box.replaceChildren();if(selected.length!==2){box.append(node('p',tr('اختار دليلًا ثانيًا.','Select a second item.')));return;}const rule=DEDUCTIONS.find(r=>selected.includes(r.a)&&selected.includes(r.b));if(!rule){box.append(node('p',tr('الدليلان لا يثبتان استنتاجًا مباشرًا. اقرأ الملاحظات وابحث عن علاقة التوقيت أو التوقيع أو المحو.','These items do not directly prove a conclusion. Read the notes and look for a timeline, signature, or erasure connection.')));return;}box.append(node('p',tr('ما الذي يثبته الربط؟','What does this connection establish?')));button(box,T(rule.label),()=>{deduce(state,selected[0],selected[1],rule.id);const row=document.querySelector('[data-deduction="'+rule.id+'"]');if(row)row.textContent='✓ '+T(rule.label);save();renderChrome();box.replaceChildren(node('p',tr('استنتاج موثّق: ','Deduction established: ')+T(rule.label)));audio.play('echo');});button(box,T(rule.wrong),()=>{box.append(node('p',tr('الدليل لا يدعم هذا الادعاء. راجع المعلومات المكتوبة.','The evidence does not support that claim. Review the written facts.')));},'quiet');},'evidence-card');b.dataset.evidence=id;b.append(node('strong',T(e.title)),node('span',T(e.note)));}
 if(!list.childElementCount)list.append(node('p',tr('الدفتر فاضي. ابدأ بفحص الورق والأجهزة.','The journal is empty. Start by inspecting documents and devices.')));
 const linked=node('div');linked.append(node('h3',tr('الاستنتاجات المثبتة','Established deductions')));for(const d of DEDUCTIONS){const row=node('p',(state.deductions[d.id]?'✓ ':'— ')+T(d.label));row.dataset.deduction=d.id;linked.append(row);}$('modal-content').append(linked);
}
function settings(){openModal(tr('الإعدادات والحفظ','SETTINGS & SAVES'),'settings');const prefs=state?.settings||menuSettings;
 for(const[key,ar,en]of[['master','الصوت العام','Master volume'],['music','الموسيقى','Music'],['ambience','البيئة','Ambience'],['effects','المؤثرات','Effects']]){const row=node('label',undefined,'settings-row');row.append(node('span',tr(ar,en)));const input=node('input');input.type='range';input.min='0';input.max='1';input.step='.05';input.value=prefs[key];input.oninput=()=>{prefs[key]=Number(input.value);applySettings();save();};row.append(input);$('modal-content').append(row);}
 for(const[key,ar,en]of[['muted','كتم الصوت','Mute audio'],['reducedMotion','تقليل الحركة','Reduced motion'],['captions','وصف الأصوات','Sound captions']]){const row=node('label',undefined,'settings-row');row.append(node('span',tr(ar,en)));const input=node('input');input.type='checkbox';input.checked=prefs[key];input.onchange=()=>{prefs[key]=input.checked;applySettings();save();};row.append(input);$('modal-content').append(row);}
 const displayControls=node('div',undefined,'modal-actions');button(displayControls,tr('ملء الشاشة / رجوع','Toggle fullscreen'),async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{notice('ملء الشاشة مش متاح في المتصفح ده؛ العرض المتجاوب شغال.','Fullscreen is unavailable here; the responsive layout is active.');}});$('modal-content').append(displayControls);
 const sensitivity=node('label',undefined,'settings-row');sensitivity.append(node('span',tr('سرعة استجابة العدسة','Lens response')));const inputSensitivity=node('input');inputSensitivity.type='range';inputSensitivity.min='.5';inputSensitivity.max='1.5';inputSensitivity.step='.1';inputSensitivity.value=prefs.lensSensitivity||1;inputSensitivity.oninput=()=>{prefs.lensSensitivity=Number(inputSensitivity.value);physics.lensSensitivity=prefs.lensSensitivity;save();};sensitivity.append(inputSensitivity);$('modal-content').append(sensitivity);
 const row=node('label',undefined,'settings-row');row.append(node('span',tr('حجم النص','Text size')));const size=node('select');size.setAttribute('aria-label',tr('حجم النص','Text size'));for(const[v,label]of[[1,'100%'],[1.2,'120%'],[1.4,'140%']]){const op=node('option',label);op.value=v;size.append(op);}size.value=prefs.textSize;size.onchange=()=>{prefs.textSize=Number(size.value);applySettings();save();};row.append(size);$('modal-content').append(row);
 $('modal-content').append(node('p',tr('الحفظ محلي على الجهاز. لن يتزامن تلقائيًا بين الأجهزة أو التطبيق والمتصفح. صدّر الملف وانقله يدويًا.','Saves stay on this device. They do not automatically sync across devices or between app and browser. Export a file to transfer them manually.')));
 const controls=node('div',undefined,'modal-actions');button(controls,tr('تصدير الحفظ','Export save'),()=>{const s=state||saved;if(!s)return;const blob=new Blob([JSON.stringify(s,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=node('a');a.href=url;a.download='echoes-save-day-'+s.day+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});const input=node('input');input.type='file';input.accept='.json,application/json';input.hidden=true;input.onchange=async()=>{const f=input.files?.[0];if(!f)return;try{if(f.size>1_000_000)throw Error('File too large');const s=store.import(await f.text());closeModal();resume(s);notice('تم استيراد الحفظ واستعادة الوردية.','Save imported; shift restored.');}catch{notice('ملف الحفظ غير صالح. حفظك الحالي لم يتغير.','Invalid save file. Your current save was not changed.');}};button(controls,tr('استيراد حفظ','Import save'),()=>input.click());$('modal-content').append(controls,input);menuSettings=prefs;}
function credits(){openModal(tr('عن اللعبة','ABOUT THE GAME'),'credits');for(const line of [CREDIT,COPYRIGHT,tr('أصول بيكسل أصلية ورسومات شخصية مخصصة. أصوات التصادم: Kenney، CC0. بقية الخلفيات الصوتية مصممة محليًا.','Original pixel artwork and character sprites. Collision recordings: Kenney, CC0. Other sound beds are original local sound design.'),tr('الإصدار 2.1.0. خمس عشرة وردية وثماني نهايات. مكتب تفاعلي وعدسة وختم فعلي على الورق.','Version 2.1.0. Fifteen shifts and eight endings. A tactile desk, working lens and stamps that contact paper.')])$('modal-content').append(node('p',line));for(const[label,path]of[['Asset credits','ASSET_CREDITS.md'],['Audio credits','AUDIO_CREDITS.md'],['Privacy','privacy.html']]){const a=node('a',label);a.href=path;if(globalThis.ECHO_PREVIEW)a.addEventListener('click',e=>{e.preventDefault();closeModal();const target=document.getElementById(path==='privacy.html'?'privacy-preview':'preview-licenses');if(target){target.open=true;target.scrollIntoView();}});$('modal-content').append(a,node('br'));}}
$('language').onclick=()=>{language=language==='ar'?'en':'ar';const opened=modalType;render();save();if(opened==='settings')settings();if(opened==='journal')openJournal();if(opened==='database')openDatabase();if(opened==='credits')credits();if(opened==='report')deskUI.report();if(opened==='shop')deskUI.shop();};$('settings').onclick=settings;$('credits').onclick=credits;$('journal').onclick=openJournal;
$('menu-button').onclick=()=>{audio.stopEffects();save();menuSettings={...state.settings};state=null;render();};
$('place-paper').onclick=()=>{if(!state||state.cinematic)return;state.world.lamp=true;desk.examine(state);notice('العدسة والضوء فوق الأثر. استنى اكتمال الفحص.','Lens and light aligned over the trace. Wait for the examination.');save();};
$('reset-props').onclick=()=>{physics.reset();notice('الأشياء رجعت لمكان آمن على المكتب.','Objects returned to safe positions on the desk.');save();};
$('skip-cinema').onclick=()=>{if(state?.cinematic){audio.stopEffects();state.cinematic=0;cinemaTime=0;render();save();}};
// A single Pointer Events path is used for mouse, touch and pen. Cancellation never activates a choice.
let pointer=null;const canvas=$('scene');const point=e=>toWorld(e.clientX,e.clientY,canvas.getBoundingClientRect());
canvas.addEventListener('pointerdown',e=>{if(pointer||!e.isPrimary||e.button>0||!state||state.cinematic||$('modal').open)return;audio.unlock();const p=point(e),body=physics.hit(p,e.pointerType==='touch'?3:0,b=>b.id!=='key'||state.flags.key);pointer={id:e.pointerId,start:p,body:body?.id,moved:false};if(desk.press)return;if(body){physics.grab(body.id,p);audio.play(['paper','record','folder'].includes(body.id)?'paper-0':body.id==='lens'?'glass-0':'wood-0',{volume:.18});}canvas.setPointerCapture(e.pointerId);e.preventDefault();});
canvas.addEventListener('pointermove',e=>{const p=point(e);if(pointer?.id===e.pointerId){pointer.moved ||=Math.hypot(p.x-pointer.start.x,p.y-pointer.start.y)>4;physics.move(p);e.preventDefault();}else renderer.hover=HOTSPOTS.find(h=>p.x>=h.rect[0]&&p.x<=h.rect[0]+h.rect[2]&&p.y>=h.rect[1]&&p.y<=h.rect[1]+h.rect[3])?.id;});
function endPointer(e,cancel=false){if(!pointer||e.pointerId!==pointer.id)return;const old=pointer,p=point(e);physics.release(cancel);pointer=null;if(canvas.hasPointerCapture(e.pointerId))canvas.releasePointerCapture(e.pointerId);const target=document.elementFromPoint(e.clientX,e.clientY)?.closest('#actions button');$('actions').querySelectorAll('button').forEach(b=>b.classList.remove('stamp-target'));
 if(!cancel&&old.body==='seal'&&old.moved&&p.x>=0&&p.x<=480&&p.y>=197&&p.y<=420){desk.stamp(state,ensureDesk(state).mode,false);}else if(!cancel&&old.body==='key'&&old.moved){desk.key(state);}else if(!cancel&&!old.moved){if(old.body==='paper'){ensureDesk(state).opened=!ensureDesk(state).opened;audio.play('paper-1');renderDeskControls();}else if(old.body==='folder'){ensureDesk(state).folderOpen=!ensureDesk(state).folderOpen;audio.play('paper-0');renderDeskControls();}else if(old.body==='torch'){ensureDesk(state).torchOn=!ensureDesk(state).torchOn;renderDeskControls();}else if(old.body==='lens')notice('حرّك العدسة فوق الحبر الصغير ووجّه الكشاف له.','Move the lens over the microprint and direct the inspection light at it.');else if(!old.body){const h=HOTSPOTS.find(h=>p.x>=h.rect[0]&&p.x<=h.rect[0]+h.rect[2]&&p.y>=h.rect[1]&&p.y<=h.rect[1]+h.rect[3]);if(h)interact(h.id);}}
 save();}
canvas.addEventListener('pointerup',e=>endPointer(e));canvas.addEventListener('pointercancel',e=>endPointer(e,true));canvas.addEventListener('lostpointercapture',()=>{if(pointer){physics.release(true);pointer=null;}});
canvas.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();$('place-paper').click();}if(e.key==='Escape'){physics.release(true);pointer=null;}});
window.addEventListener('resize',()=>{layoutContext();physics.release(true);pointer=null;});
document.addEventListener('visibilitychange',()=>{audio.visibility(document.hidden);if(document.hidden){physics.release(true);pointer=null;save();}lastFrame=0;});window.addEventListener('pagehide',save);
function imprint(dt){const s=state,p=physics.body('paper');if(!s||s.cinematic)return;const inLight=s.world.lamp&&Math.abs(p.x-261)<25&&Math.abs(p.y-215)<28;imprintTime=inLight?Math.min(1.2,imprintTime+dt):Math.max(0,imprintTime-dt*2);s.world.imprint=imprintTime/1.2;$('imprint-fill').style.width=(s.world.imprint*100)+'%';if(imprintTime<1.2)return;
 const id=s.day>=14&&s.evidence.self?'erasure':s.day>=5&&s.evidence.transfer?'signature':s.day>=2?'researcher':null;
 if(id&&!s.evidence[id]){fileEvidence(id);lastImprint=id;renderChrome();save();}else if(!id&&lastImprint!=='tutorial'){lastImprint='tutorial';notice('الحبر عادي حاليًا. جرّب الورق الذي سيصل في الأيام القادمة.','The ink is ordinary for now. Try documents arriving in later shifts.');}}
let cinemaCueKey='';
const CINEMA_CUES=[['step-0',bi('الطابور يتحرك','The queue moves')],['printer',bi('نسخة تخرج دون طلب','An unrequested copy prints')],['step-1',bi('خطوات في الممر','Footsteps down the corridor')],['creature-field',bi('محمود يكافح لالتقاط أنفاسه','Mahmoud struggles to breathe')],['paper-0',bi('ورقة النقل تحت القفل','A transfer sheet beneath the lock')],['step-0',bi('خطوات ياسر تقترب','Yasser’s footsteps approach')],['hum',bi('الشارع يهدأ تحت الحظر','The street falls quiet under curfew')],['paper-1',bi('هالة تقلب دفتر المرضى','Hala turns her patient ledger')],['metal-0',bi('رنة مفتاح مكتومة','A muffled key chime')],['creature-field',bi('خدش وطرق عند الباب','Scratching and a knock at the door')],['hum',bi('ضوء واحد فوق الناجين','One light above the survivors')],['breath',bi('نَفَس وراء زجاج الغرفة','Breathing behind the chamber glass')],['printer',bi('آخر نسخة من البروتوكول','The last protocol copy')],['echo',bi('صدى جلسة الذاكرة','An echo of the memory session')],['paper-0',bi('الملف الأخير يُفتح','The final file opens')]];
function frame(tm){const dt=lastFrame?Math.min(.08,(tm-lastFrame)/1000):0;lastFrame=tm;if(!document.hidden){if(state&&!$('modal').open){if(state.cinematic){cinemaTime+=dt;const key=state.seed+':'+state.cinematic+':'+state.ending;if(cinemaTime>.35&&key!==cinemaCueKey){cinemaCueKey=key;const cue=state.cinematic===16?['echo',bi('أثر القرار الأخير','The final decision resonates')]:CINEMA_CUES[state.day-1];audio.play(cue[0],{category:cue[0]==='creature-field'?'creatures':'cinematics',volume:.35,x:state.day%2?180:300,caption:T(cue[1])});}const duration=state.cinematic===16?6:CINEMATICS[state.cinematic-1].duration;$('cinema-progress').style.width=Math.min(100,cinemaTime/duration*100)+'%';if(cinemaTime>=duration){state.cinematic=0;cinemaTime=0;render();save();}}else{
 physics.update(dt,state.world.window?3:0);desk.update(state,dt);$('imprint-fill').style.width=(state.world.imprint*100)+'%';const w=state.world;if(w.printer==='printing'){printTimer+=dt;if(printTimer>=2.8){w.printer='ready';printTimer=0;notice('النسخة جاهزة. اضغط الطابعة لجمعها.','Copy ready. Tap the printer to collect it.');audio.play('paper-0',{x:394});save();}}
 w.noise=Math.max(0,w.noise-dt*.025);if(state.day>=10&&state.day<15&&!w.lights){w.threat=Math.min(1,w.threat+dt*w.noise*.05);}else w.threat=Math.max(0,w.threat-dt*.2);if(w.threat>.8&&w.door){w.door=false;w.barricade=true;w.noise=0;audio.play('wood-1',{caption:tr('المكتب سَدّ الباب؛ الضوء يوقف الاقتراب.','The desk blocked the door; light stops the approach.'),x:448});save();}
 }}renderer.draw(state,physics,dt,cinemaTime);audio.update(state,state?.cinematic);if(captionTimer>0){captionTimer-=dt;if(captionTimer<=0)$('sound-caption').textContent='';}}requestAnimationFrame(frame);}
let deferredInstall;
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e;});$('install').onclick=async()=>{if(deferredInstall){await deferredInstall.prompt();deferredInstall=null;}else{openModal(tr('تثبيت اللعبة','INSTALL THE GAME'),'install');$('modal-content').append(node('p',tr('على iPhone: افتح في Safari ثم مشاركة ← إضافة إلى الشاشة الرئيسية. على Android والكمبيوتر: اختار تثبيت التطبيق من قائمة المتصفح إذا كانت متاحة. افتح اللعبة مرة متصلًا لتحميل ملفات اللعب دون إنترنت.','On iPhone: open in Safari, then Share → Add to Home Screen. On Android or desktop: choose Install app in the browser menu when available. Open the game once online to cache its offline files.')));}};
if(Capacitor.isNativePlatform()){
 NativeApp.addListener('appStateChange',({isActive})=>{audio.visibility(!isActive);if(!isActive){physics.release(true);pointer=null;save();}lastFrame=0;});
 NativeApp.addListener('backButton',()=>{if($('modal').open){closeModal();return;}if(state?.cinematic){$('skip-cinema').click();return;}if(state){save();openModal(tr('اللعبة متوقفة','GAME PAUSED'),'pause');button($('modal-content'),tr('متابعة','Resume'),closeModal);button($('modal-content'),tr('حفظ والعودة للقائمة','Save and return to menu'),()=>{save();state=null;closeModal();render();});}else NativeApp.exitApp();});
}
render();audio.unlock().catch(()=>{});if(store.error)notice('تعذرت استعادة الحفظ؛ يمكنك استيراد نسخة من الإعدادات.','Save recovery was incomplete; import a backup from Settings.');
renderer.load().then(()=>{$('loading').hidden=true;if(renderer.failed.length)notice('تعذّر تحميل بعض الرسومات. جرّب إعادة تحميل الصفحة.','Some artwork could not load. Try refreshing.');requestAnimationFrame(frame);});
if('serviceWorker' in navigator&&!globalThis.ECHO_PREVIEW&&location.protocol!=='file:'&&!window.Capacitor?.isNativePlatform?.()){navigator.serviceWorker.register('./sw.js',{scope:'./'}).then(reg=>{reg.addEventListener('updatefound',()=>{const worker=reg.installing;worker?.addEventListener('statechange',()=>{if(worker.state==='installed'&&navigator.serviceWorker.controller)notice('تحديث جاهز؛ هيتطبق بعد إغلاق كل نوافذ اللعبة وفتحها.','Update ready; it will apply after all game windows are closed and reopened.');});});}).catch(()=>notice('اللعب متاح؛ التخزين دون اتصال غير متاح الآن.','Gameplay is available; offline caching is unavailable right now.'));}
