import {DEDUCTIONS} from './content.js';
const API='https://fpkwnkjtkctwextxkyfb.supabase.co/rest/v1/rpc/';
// Public publishable browser key. Authorization is enforced by the RPCs and DB grants.
const KEY='sb_publishable_kyDquG-S7yrXK27dngHyZA_EW5CRXIw';
const names={true:['النهاية الحقيقية','True ending'],truth:['الحقيقة','The truth'],silence:['الصمت','Silence'],surv:['النجاة','Survival'],inf:['العدوى','Infection'],sac:['التضحية','Sacrifice'],loop:['الحلقة','The loop'],file:['الملف','The file'],hala_aided:['التعاون مع هالة','Aided Hala'],yasser_aided:['التعاون مع ياسر','Aided Yasser'],supplies_shared:['تقاسم المؤن','Shared supplies'],infected:['مصاب عند النهاية','Infected at ending'],all_deductions:['أكمل الاستنتاجات','Completed deductions'],patient07:['اكتشف مريض ٠٧','Found Patient 07'],no_review_errors:['راجع الطلبات دون أخطاء','No review errors'],echo_preserved:['حافظ على ملفات Echo','Preserved Echo files'],self_found:['اكتشف ملفه','Found personal file']};
export function outcomes(s){const m={infected:!!s.infection,all_deductions:DEDUCTIONS.every(d=>s.deductions[d.id]),patient07:!!s.evidence.s07,echo_preserved:!!s.flags.echo&&!s.flags.wipe,self_found:!!s.flags.self};for(const[day,k,flag]of[[6,'yasser_aided','sec'],[8,'hala_aided','doc'],[11,'supplies_shared','share']])if(s.log.some(r=>r.day===day&&r.flag))m[k]=!!s.flags[flag];const cases=s.log.filter(r=>r.case);if(cases.length>=8)m.no_review_errors=cases.every(r=>r.correct);return m;}
async function rpc(name,payload){const c=new AbortController(),timer=setTimeout(()=>c.abort(),12000);try{const r=await fetch(API+name,{method:'POST',headers:{apikey:KEY,'Content-Type':'application/json'},body:JSON.stringify(payload||{}),signal:c.signal,cache:'no-store'});if(!r.ok)throw Error('RPC '+r.status);return await r.json();}finally{clearTimeout(timer);}}
function el(tag,text){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;return n;}
let panel,active='',busy=false;
function load(){let s;try{s=JSON.parse(localStorage.getItem('echoes.save.v3')||'null');}catch{return;}if(!s||s.phase!=='ending'||s.cinematic){if(panel)panel.hidden=true;active='';return;}const id=s.seed+':'+s.ending+':'+s.language;if(active===id)return;active=id;const en=s.language==='en',tr=(a,b)=>en?b:a;
 if(!panel){panel=el('section');panel.id='echo-ending-stats';panel.className='ending-stats';document.querySelector('.main-column').append(panel);}panel.hidden=false;panel.replaceChildren();panel.dir=en?'ltr':'rtl';panel.append(el('h2',tr('نتائج الوردية — مشاركة اختيارية','Run outcomes — optional sharing')));const consent=el('label');consent.className='echo-consent';const check=el('input');check.type='checkbox';check.id='echo-ending-consent';consent.append(check,el('span',tr('أوافق على إرسال فئة النهاية ونتائج مختصرة (قرارات وأدلة وأخطاء)، مع إيصال عشوائي لهذه الحكاية لمنع إعادة الإرسال. لا أسماء أو بريد أو ملف حفظ. قد تعالج جهة الخدمة عنوان الاتصال؛ يُستخدم ملخص يومي منه لتقييد الإرسال. المشاركة المسجلة لا يمكن سحبها من هذه الشاشة.','I agree to share the ending and brief outcomes (choices, clues, mistakes), with a random receipt for this run to prevent retries being counted twice. No names, email or save file. The service may process network addresses; a daily hash is used for submission limits. A recorded submission cannot be withdrawn from this screen.')));panel.append(consent);
 const share=el('button',tr('شارك واعرض النتائج','Share and view results'));share.className='echo-share-button';share.disabled=true;const show=el('button',tr('اعرض الإحصائيات فقط','View statistics only'));show.className='secondary';const status=el('p',tr('لم نرسل أي بيانات.','Nothing has been sent.'));status.className='echo-status';status.setAttribute('role','status');const list=el('div');list.className='echo-vote-list';const legacy=el('button',tr('نتائج التصويت القديم','Legacy ending poll'));legacy.className='secondary';panel.append(share,show,legacy,status,list,el('p',tr('النسب محسوبة على الحكايات المشاركة المؤهلة لكل سؤال، وليست عدد أشخاص فريدين. الحماية تمنع التكرار البسيط وتحدّ الطلبات؛ لا تثبت أن الحكاية لُعبت فعلًا.','Percentages use eligible submitted runs for each question, not unique people. Validation, idempotency and throttling limit simple duplicates and floods; they do not prove a run was played.')));
 check.onchange=()=>{share.disabled=!check.checked||busy;};
 async function display(){const rows=await rpc('echo_get_run_stats');list.replaceChildren();for(const r of rows){const key=r.metric.replace('ending:',''),label=names[key]?.[en?1:0]||key,n=Number(r.eligible),v=Number(r.positive),row=el('div');row.className='echo-vote-row';row.append(el('span',label),el('strong',n<5?tr(`${v} من ${n} — عينة غير كافية`,`${v} of ${n} — insufficient sample`):`${v} / ${n} · ${(100*v/n).toFixed(1)}%`));list.append(row);}}
 show.onclick=async()=>{if(busy)return;busy=true;show.disabled=true;status.textContent=tr('جارٍ جلب المجاميع دون إرسال نتيجة لعبك…','Fetching aggregates without submitting your run…');try{await display();status.textContent=tr('تم عرض العينة الفعلية. لم نرسل نتيجة لعبك.','Actual sample displayed. Your run was not submitted.');}catch{status.textContent=tr('الاتصال غير متاح؛ اللعب والحفظ المحلي مستمران.','Connection unavailable; play and local saves remain available.');}finally{busy=false;show.disabled=false;}};
 legacy.onclick=async()=>{if(busy)return;busy=true;legacy.disabled=true;try{const rows=await rpc('echo_get_ending_stats');list.replaceChildren();for(const r of rows){const n=Number(r.total_votes),v=Number(r.vote_count),row=el('div');row.className='echo-vote-row';row.append(el('span',names[r.ending_key]?.[en?1:0]||r.ending_key),el('strong',n<5?`${v} / ${n} — `+tr('عينة غير كافية','insufficient sample'):`${v} / ${n} · ${(v/n*100).toFixed(1)}%`));list.append(row);}status.textContent=tr('التصويت القديم على فئة النهاية فقط؛ عينة منفصلة، وليست حكايات موثقة أو أشخاصًا فريدين.','Legacy ending-only opt-in poll: a separate sample, not verified runs or unique people.');}catch{status.textContent=tr('تعذّر جلب المجاميع القديمة.','Could not fetch legacy totals.');}finally{busy=false;legacy.disabled=false;}};
 share.onclick=async()=>{if(busy||!check.checked)return;busy=true;share.disabled=true;const storageKey='echoes.run-receipt.v1:'+s.seed;try{let receipt=localStorage.getItem(storageKey);if(!receipt){receipt=crypto.randomUUID();localStorage.setItem(storageKey,receipt);}const payload={p_run_id:receipt,p_ending_key:s.ending,p_metrics:outcomes(s)};const result=await rpc('echo_submit_run',payload);status.textContent=result.duplicate?tr('الإيصال مسجل بالفعل؛ لم نكرر المشاركة.','Receipt already recorded; no duplicate counted.'):tr('تم تسجيل المشاركة.','Submission recorded.');await display();}catch{status.textContent=tr('لم نتمكن من تأكيد الإرسال. لو انقطع الرد، إعادة المحاولة بنفس الإيصال لن تضاعف المشاركة. حد الإرسال: ٣ بالدقيقة و٢٠ باليوم لكل عنوان اتصال كما يصل للخدمة.','Could not confirm submission. Retrying the same receipt cannot double-count. Limits: 3/minute and 20/day per gateway-reported address.');}finally{busy=false;share.disabled=!check.checked;}};
}
if(typeof window!=='undefined')setInterval(load,600);
