import {test,expect} from '@playwright/test';
import {fresh,SAVE_KEY} from '../../src/core.js';import {DECISIONS,DEDUCTIONS,EVIDENCE} from '../../src/content.js';
const getState=page=>page.evaluate(key=>JSON.parse(localStorage.getItem(key)),SAVE_KEY);
async function boot(page,seed=2,initial={}){const s=fresh(seed,'en');Object.assign(s,initial);s.settings.reducedMotion=true;await page.addInitScript(({s,key})=>{if(!sessionStorage.getItem('test-seeded')){localStorage.setItem(key,JSON.stringify(s));sessionStorage.setItem('test-seeded','1');}},{s,key:SAVE_KEY});await page.goto('./');await expect(page.locator('#loading')).toBeHidden();await page.getByRole('button',{name:'Continue saved run',exact:true}).click();}
async function skip(page){if(await page.locator('#cinematic').isVisible())await page.locator('#skip-cinema').click();}
async function tool(page,id){await page.locator(`[data-tool="${id}"]`).click();}
async function searchRecord(page,q,print=false){await tool(page,'computer');await page.getByRole('searchbox').fill(q);const button=page.getByRole('button',{name:print?'Print a copy':'Inspect and file information',exact:true});await button.first().click();if(!print)await page.locator('#close-modal').click();}
async function reveal(page){await page.locator('#place-paper').click();await expect.poll(async()=>Object.keys((await getState(page)).evidence)).toContain((await getState(page)).day>=14?'erasure':(await getState(page)).day>=5?'signature':'researcher');}
async function drag(page,id,to){await page.locator('#scene').scrollIntoViewIfNeeded();const rect=await page.locator('#scene').boundingBox(),s=await getState(page),from=s.props.find(p=>p.id===id);const a={x:rect.x+from.x/480*rect.width,y:rect.y+from.y/420*rect.height},b={x:rect.x+to.x/480*rect.width,y:rect.y+to.y/420*rect.height};
 if(test.info().project.use.hasTouch){const client=await page.context().newCDPSession(page);await client.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:a.x,y:a.y}]});for(let i=1;i<=12;i++){await client.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:a.x+(b.x-a.x)*i/12,y:a.y+(b.y-a.y)*i/12}]});await page.waitForTimeout(17);}await client.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await client.detach();}else{await page.mouse.move(a.x,a.y);await page.mouse.down();await page.mouse.move(b.x,b.y,{steps:12});await page.waitForTimeout(250);await page.mouse.up();}
}
test('complete representative campaign, all daily films, physical clues, four deductions and true ending',async({page})=>{const errors=[];page.on('pageerror',e=>errors.push(e.message));await boot(page);let films=0;
 for(let day=1;day<=15;day++){await expect(page.locator('#day-number')).toHaveText(String(day).padStart(2,'0'));await expect(page.locator('#cinematic')).toBeVisible();films++;await skip(page);
  if([2,5,8,12,14].includes(day)){await page.getByRole('button',{name:'Inspect the researcher’s visit',exact:true}).click();await page.getByRole('button',{name:'Compare identities and file the trace'}).click();}
  if(day<=4){await page.getByRole('button',{name:'Receive citizen',exact:true}).click();while((await getState(page)).phase==='citizen'){const s=await getState(page),c=s.cases[day][s.caseIndex];await tool(page,'scanner');await page.getByRole('button',{name:{ok:'Approve with seal',no:'Reject / correct',fl:'Flag anomaly'}[c.a],exact:true}).click();await expect.poll(async()=>(await getState(page)).phase).toBe('result');await page.locator('#actions button').first().click();}await expect.poll(async()=>(await getState(page)).phase).toBe('dayEnd');await page.getByRole('button',{name:'Start next day',exact:true}).click();}
  else if(day<15){const tools={5:'drawer',6:'camera',7:'window',9:'phone',10:'door',11:'lights'};if(tools[day])await tool(page,tools[day]);if(day===8)await searchRecord(page,'4410');if(day===12)await searchRecord(page,'S07');if(day===14)await searchRecord(page,'YOU');if(day===13){await searchRecord(page,'ECHO',true);await expect(page.locator('#notice')).toContainText('Copy ready',{timeout:10000});await tool(page,'printer');}
   if(day===5||day===14)await reveal(page);
   await page.getByRole('button',{name:DECISIONS[day-5][1][1],exact:true}).click();
   if(day===9){await tool(page,'archive');for(const[id,to]of[['paper',{x:280,y:207}],['seal',{x:330,y:208}],['key',{x:149,y:210}]]){const before=(await getState(page)).props.find(p=>p.id===id).x;await drag(page,id,to);const after=(await getState(page)).props.find(p=>p.id===id).x;expect(Math.abs(after-before)).toBeGreaterThan(3);}await page.locator('#reset-props').click();}
   await page.getByRole('button',{name:'Start next day',exact:true}).click();
  }else{
   await page.locator('#journal').click();for(const rule of DEDUCTIONS){const selected=page.locator('.evidence-card.selected');while(await selected.count())await selected.first().click();await page.locator(`[data-evidence="${rule.a}"]`).click();await page.locator(`[data-evidence="${rule.b}"]`).click();await page.getByRole('button',{name:rule.wrong.en,exact:true}).click();await expect(page.locator('.deduction-box')).toContainText('does not support');await page.getByRole('button',{name:rule.label.en,exact:true}).click();}
   await page.locator('#close-modal').click();await expect(page.locator('#links-count')).toHaveText('4/4');await page.getByRole('button',{name:'Reveal the truth',exact:true}).click();await expect(page.locator('#cinema-title')).toHaveText('TRUE ENDING');await skip(page);await expect(page.locator('#story-title')).toHaveText('TRUE ENDING');
  }
 }
 expect(films).toBe(15);expect((await getState(page)).ending).toBe('true');expect(errors).toEqual([]);await page.screenshot({path:`test-results/${test.info().project.name}-ending.png`,fullPage:true});
});
test('refusing all help still reaches an ending through restricted-record alternatives',async({page})=>{await boot(page,3,{day:5,phase:'investigate',cinematic:5});for(let day=5;day<=15;day++){await skip(page);if(day===15){await page.getByRole('button',{name:'Leave the city',exact:true}).click();await skip(page);await expect(page.locator('#story-title')).toHaveText('THE SURVIVOR');break;}const tools={5:'drawer',6:'camera',7:'window',9:'phone',10:'door',11:'lights'};if(tools[day])await tool(page,tools[day]);if(day===8)await searchRecord(page,'4410');if(day===12)await searchRecord(page,'S07');if(day>=13){await tool(page,'computer');await page.getByRole('searchbox').fill(day===13?'ECHO':'YOU');await page.getByRole('button',{name:'Record the access refusal and continue'}).click();}await page.getByRole('button',{name:day===13?'Leave the files sealed':DECISIONS[day-5][2][1],exact:true}).click();await page.getByRole('button',{name:'Start next day',exact:true}).click();}expect((await getState(page)).evidence.echo).toBeFalsy();});

test('cinematic naturally completes, sprites animate, every sound decodes, and privacy remains available offline',async({page,context})=>{await boot(page,4,{settings:{...fresh(4).settings,reducedMotion:false}});await expect(page.locator('#cinematic')).toBeHidden({timeout:12000});await page.getByRole('button',{name:'Receive citizen',exact:true}).click();const before=await page.locator('#scene').evaluate(c=>c.toDataURL());await page.waitForTimeout(500);expect(await page.locator('#scene').evaluate(c=>c.toDataURL())).not.toBe(before);const decoded=await page.evaluate(async()=>{const m=await(await fetch('./audio-manifest.json')).json(),ctx=new AudioContext();let count=0;for(const a of m.assets){const res=await fetch('./'+a.file);if(!res.ok)throw Error(a.file);const b=await ctx.decodeAudioData(await res.arrayBuffer());if(b.duration>0)count++;}await ctx.close();return count;});expect(decoded).toBe(22);await page.evaluate(()=>navigator.serviceWorker.ready);await expect.poll(()=>page.evaluate(()=>!!navigator.serviceWorker.controller)).toBe(true);await context.setOffline(true);await page.goto('./privacy.html');await expect(page.getByRole('heading',{name:'Privacy policy',exact:true})).toBeVisible();});

test('language switches, save resumes exact citizen, no cropping, audio control and fresh run diversity',async({page})=>{await boot(page,1);await skip(page);await page.getByRole('button',{name:'Receive citizen'}).click();const first=await page.locator('#dialogue').textContent();await tool(page,'scanner');await page.locator('#language').click();await expect(page.locator('html')).toHaveAttribute('dir','rtl');await expect(page.locator('#story-title')).toContainText('بدل فاقد');await page.reload();await expect(page.locator('#loading')).toBeHidden();await page.getByRole('button',{name:'كمّل من الحفظ'}).click();expect((await getState(page)).phase).toBe('citizen');expect((await getState(page)).inspected['2850602']).toBeTruthy();await page.locator('#language').click();await page.locator('#settings').click();await page.getByLabel('Mute audio',{exact:true}).check();await page.getByRole('combobox',{name:'Text size',exact:true}).selectOption('1.4');await page.locator('#close-modal').click();expect((await getState(page)).settings.muted).toBe(true);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await page.screenshot({path:`test-results/${test.info().project.name}-game.png`,fullPage:true});await page.locator('#menu-button').click();await page.getByRole('button',{name:'Start a new run',exact:true}).click();await page.getByRole('button',{name:'Start over',exact:true}).click();await skip(page);await page.getByRole('button',{name:'Receive citizen'}).click();expect(await page.locator('#dialogue').textContent()).not.toBe(first);expect((await getState(page)).evidence).toEqual({});});
test('all game files cache and reload offline; cancellation does not make a decision',async({page,context})=>{const errors=[];page.on('pageerror',e=>errors.push(e.message));await boot(page);await skip(page);await page.getByRole('button',{name:'Receive citizen'}).click();await page.evaluate(async()=>{await navigator.serviceWorker.ready;});await expect.poll(()=>page.evaluate(()=>!!navigator.serviceWorker.controller)).toBe(true);await expect.poll(()=>page.evaluate(async()=>{const keys=await caches.keys();return(await(await caches.open(keys.find(k=>k.startsWith('echoes-')))).keys()).length;})).toBeGreaterThan(40);
 const before=(await getState(page)).phase;await page.locator('#scene').scrollIntoViewIfNeeded();const r=await page.locator('#scene').boundingBox();await page.mouse.move(r.x+r.width*.73,r.y+r.height*.8);await page.mouse.down();await page.locator('#scene').dispatchEvent('pointercancel',{pointerId:1,isPrimary:true,clientX:r.x+r.width*.73,clientY:r.y+r.height*.8});await page.mouse.up();expect((await getState(page)).phase).toBe(before);
 await context.setOffline(true);await page.reload();await expect(page.locator('#loading')).toBeHidden();await page.getByRole('button',{name:'Continue saved run'}).click();await tool(page,'scanner');await page.getByRole('button',{name:'Approve with seal'}).click();await expect(page.locator('#dialogue')).toContainText('Verified decision');expect(errors).toEqual([]);});
