import test from 'node:test';import assert from 'node:assert/strict';import {fresh,validateSave,currentCase} from '../src/core.js';import {Physics} from '../src/physics.js';import {Desk,purchase,settleDay,Materials} from '../src/desk.js';
function setup(){const s=fresh(1,'en');s.cinematic=0;s.phase='citizen';const p=new Physics(),events=[];const d=new Desk(p,(...args)=>events.push(args));d.bind(s);return{s,p,d,events};}
function run(x,time=.6,fps=60){for(let i=0;i<fps*time;i++){x.p.update(1/fps);x.d.update(x.s,1/fps);}}
test('stamp must contact an unfolded eligible document; marks move with paper and survive reload',()=>{const x=setup();assert.equal(x.d.stamp(x.s,'ok'),false);x.s.desk.opened=false;assert.equal(x.d.stamp(x.s,'ok',true),false);x.s.desk.opened=true;assert.equal(x.d.stamp(x.s,'ok',true),true);run(x);assert.equal(x.s.phase,'result');assert.equal(x.s.desk.marks.length,1);assert.equal(x.events.filter(e=>e[0]==='stamp').length,1);const m={...x.s.desk.marks[0]};x.p.place('paper',270,290);assert.equal(x.s.desk.marks[0].x,m.x);assert.equal(validateSave(x.s).desk.marks[0].choice,'ok');assert.equal(validateSave(x.s).log[0].correct,true);});
test('flagging requires actual inspection and stamp cancellation cannot decide',()=>{const x=setup();assert.equal(x.d.stamp(x.s,'fl',true),false);x.p.grab('seal',{x:400,y:320});x.p.release(true);run(x);assert.equal(x.s.phase,'citizen');assert.equal(x.s.desk.marks.length,0);});
test('lens requires aligned light and open paper; upgrade is convenience only',()=>{const x=setup();x.s.day=5;x.s.evidence.transfer={day:5};x.s.phase='investigate';x.d.bind(x.s);x.d.examine(x.s);x.s.desk.torchOn=false;x.s.world.lamp=false;run(x,2);assert.equal(x.s.evidence.signature,undefined);x.s.desk.torchOn=true;run(x,2);assert.equal(x.s.evidence.signature.day,5);});
test('archive opens only for Samir’s matching key at the lock',()=>{const x=setup();assert.equal(x.d.key(x.s,true),false);x.s.flags.key=true;assert.equal(x.d.key(x.s),false);assert.equal(x.d.key(x.s,true),true);assert.equal(x.s.world.archive,true);assert.equal(x.s.evidence.deleted.day,1);});
test('daily accounts and equipment are idempotent across save reload',()=>{const x=setup();x.d.stamp(x.s,'ok',true);run(x);const a=settleDay(x.s),balance=x.s.desk.credits;settleDay(x.s);assert.equal(x.s.desk.credits,balance);assert.equal(a.approved,1);const s=validateSave(x.s);settleDay(s);assert.equal(s.desk.credits,balance);assert.equal(purchase(s,'lens'),true);assert.equal(purchase(s,'lens'),false);assert.equal(purchase(s,'light'),false);assert.equal(validateSave(s).desk.upgrades.lens,true);});
test('wet ink spreads, then dries; local simulation stays bounded',()=>{const x=setup();x.s.desk.wet=.8;x.d.stamp(x.s,'ok',true);run(x);assert.ok(x.s.desk.marks[0].bleed>0);const b=x.s.desk.marks[0].bleed;run(x,20);assert.equal(x.s.desk.marks[0].dry,1);assert.ok(x.s.desk.marks[0].bleed>=b);for(let i=0;i<100;i++)x.d.materials.emit('spark',240,230,20);assert.ok(x.d.materials.particles.length<=96);run(x,5);assert.ok(x.d.materials.particles.length<96);});
test('stamping impact, drying and outcomes agree at 30, 60 and 120 Hz',()=>{const result=[];for(const fps of [30,60,120]){const x=setup();x.d.stamp(x.s,'ok',true);run(x,2,fps);result.push([x.s.phase,x.s.desk.marks.length,x.events.filter(e=>e[0]==='stamp').length]);}assert.deepEqual(result[0],result[1]);assert.deepEqual(result[1],result[2]);});
